name: Build OPPO K10x Kernel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Compile Kernel
    runs-on: ubuntu-24.04
    
    env:
      OPPO_K10X_RootPath: ${{ github.workspace }}/OPPO_K10X_Source

      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
      - name: Configure Fast APT Mirror
        uses: vegardit/fast-apt-mirror.sh@v1
        
      - name: Make Build Environment
        timeout-minutes: 10
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget automake flex lzop bison gperf build-essential zip curl zlib1g-dev libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3 ccache git-lfs gnupg imagemagick libelf-dev libncurses5-dev libsdl1.2-dev gpart fuse2fs e2fsck-static icu-doc rsync adb fastboot libstdc++6 python-is-python3 gcc-aarch64-linux-gnu
          mkdir -p $CCACHE_DIR
          mkdir -p ${{ env.OPPO_K10X_RootPath }}
          mkdir -p ${{ env.OPPO_K10X_RootPath }}/kernel
          ccache -M 5G

      - name: Checkout Kernel Source
        uses: actions/checkout@v6
        with:
          repository: Rancemxn/android_kernel_oppo_sm6375
          path: ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4
          ref: main
          fetch-depth: 1
          submodules: false

      - name: Checkout Modules Source
        uses: actions/checkout@v6
        with:
          repository: Rancemxn/android_kernel_modules_and_devicetree_oppo_sm6375
          path: ${{ env.OPPO_K10X_RootPath }}/temp_modules
          ref: oppo/sm6375_u_14.0.0_k10x_5g
          fetch-depth: 1

      - name: Checkout Submodules
        working-directory: ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4
        run: |
          git submodule init
          git submodule update --init --recursive

      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.ref_name }}-
            ${{ runner.os }}-ccache-

      - name: Prepare Compiler
        run: |
          mkdir -p ${{ env.OPPO_K10X_RootPath }}/compiler
          cd ${{ env.OPPO_K10X_RootPath }}/compiler
          
          curl -fL "https://github.com/Rancemxn/android_kernel_oppo_sm6375/releases/download/tool-develop/linux-x86-refs_tags_android-14.0.0_r0.140-clang-r416183b.tar.gz" -o clang-r416183b.tar.gz --connect-timeout 30 --retry 5 --retry-delay 5
          mkdir -p clang-12.0.5
          tar -xzf clang-r416183b.tar.gz -C clang-12.0.5
          rm clang-r416183b.tar.gz
          
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-9.3 aarch64-linux-android-9.3 --depth=1
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm-linux-androideabi-4.9 --depth=1

          mkdir -p ${{ env.OPPO_K10X_RootPath }}/compiler/ccache-bin
          cd ${{ env.OPPO_K10X_RootPath }}/compiler/ccache-bin
          ln -sf "$(which ccache)" clang
          ln -sf "$(which ccache)" clang++
          ln -sf "$(which ccache)" aarch64-linux-android-gcc
          ln -sf "$(which ccache)" aarch64-linux-android-g++
          ln -sf "$(which ccache)" arm-linux-androideabi-gcc
          ln -sf "$(which ccache)" arm-linux-androideabi-g++

      - name: Handle Dependencies
        working-directory: ${{ env.OPPO_K10X_RootPath }}
        run: |
          mv temp_modules/vendor ./vendor
          rm -rf temp_modules

          ln -sf ${{ env.OPPO_K10X_RootPath }}/vendor/qcom/opensource/wlan/qcacld-3.0 ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4/drivers/staging/qcacld-3.0
          ln -sf ${{ env.OPPO_K10X_RootPath }}/vendor/qcom/opensource/wlan/qca-wifi-host-cmn ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4/drivers/staging/qca-wifi-host-cmn
          ln -sf ${{ env.OPPO_K10X_RootPath }}/vendor/qcom/opensource/wlan/fw-api ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4/drivers/staging/fw-api
          ln -sf ${{ env.OPPO_K10X_RootPath }}/vendor/qcom/opensource/wlan/utils ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4/drivers/staging/utils
          echo 'source "drivers/staging/qcacld-3.0/Kconfig"' >> ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4/drivers/staging/Kconfig
          echo 'obj-$(CONFIG_QCA_CLD_WLAN) += qcacld-3.0/' >> ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4/drivers/staging/Makefile
          sed -i 's|WLAN_ROOT := drivers/staging/qcacld-3.0|WLAN_ROOT := $(srctree)/$(src)|g' "${{ env.OPPO_K10X_RootPath }}/vendor/qcom/opensource/wlan/qcacld-3.0/Kbuild"

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Compile Kernel
        working-directory: ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4
        run: |
          chmod +x build.sh
          ./build.sh
      
      - name: Show Ccache
        if: always()
        run: ccache -s

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: OPPO_K10x_Kernel_Image
          path: ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4/out/arch/arm64/boot/Image

      - name: Upload Kernel Modules
        uses: actions/upload-artifact@v6
        with:
          name: OPPO_K10x_Kernel_Modules
          path: ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4/out/all_modules/*
